In [21]:
import pandas as pd
import numpy as np
from ast import literal_eval
import re

In [22]:
pd.set_option('display.max_columns', None)

In [23]:
ruta = "C:\\Users\\LENOVO\\Desktop\\git hub\\PROYECTO FINAL\\Proyecto-final-vivienda-Madrid-Malaga-Sevilla\\bloque 3\\ALQUILER\\ANALISIS\\datos_analizar_alquiler.csv"
datos_alquiler_l = pd.read_csv(ruta)
datos_alquiler_l.head(5)

,id,titulo,localización,precio,vivienda,superficie_m2,habitaciones,baños,terraza,estado,armarios_empotrados,orientacion,año_construccion,calefaccion,aire_acondicionado,direccion,distrito,municipio,zona
0,108649983,"Alquiler de piso en calle de Juanelo, 23",Lavapiés-Embajadores,1300,piso,47,0,1,False,Segunda mano/buen estado,True,Sur,NaN,NaN,True,"Calle de Juanelo, 23",Distrito Centro,"Madrid capital, Madrid",NaN
1,100086672,Alquiler de piso en Vicente Ferrer,Malasaña-Universidad,1350,piso,60,0,1,False,Segunda mano/buen estado,True,Este,NaN,Calefacción individual,True,NaN,Distrito Centro,"Madrid capital, Madrid",NaN
2,105407203,"Alquiler de piso en calle de las Aguas, 8",Palacio,2000,piso,98,3,1,False,Segunda mano/buen estado,False,NaN,NaN,NaN,True,"Calle de las Aguas, 8",Distrito Centro,"Madrid capital, Madrid",NaN
3,99564765,Alquiler de piso en travesía de Trujillos,Sol,1580,piso,50,0,1,False,Segunda mano/buen estado,True,Sur,NaN,Eléctrica,True,NaN,Distrito Centro,"Madrid capital, Madrid",NaN
4,108651419,"Alquiler de piso en calle de Lavapiés, 40",Lavapiés-Embajadores,1850,piso,85,3,1,False,Segunda mano/buen estado,True,NaN,NaN,NaN,False,"Calle de Lavapiés, 40",Distrito Centro,"Madrid capital, Madrid",NaN

In [24]:
# Eliminar columnas
columnas_a_eliminar = [
    'direccion',
    'zona',
]
datos_alquiler_l.drop(columns=columnas_a_eliminar, inplace=True)

In [25]:
# Renombrar columna a m2
datos_alquiler_l.rename(columns={
    'superficie_m2': 'm2'
}, inplace=True)

In [26]:
datos_alquiler_l.head(5)

,id,titulo,localización,precio,vivienda,m2,habitaciones,baños,terraza,estado,armarios_empotrados,orientacion,año_construccion,calefaccion,aire_acondicionado,distrito,municipio
0,108649983,"Alquiler de piso en calle de Juanelo, 23",Lavapiés-Embajadores,1300,piso,47,0,1,False,Segunda mano/buen estado,True,Sur,NaN,NaN,True,Distrito Centro,"Madrid capital, Madrid"
1,100086672,Alquiler de piso en Vicente Ferrer,Malasaña-Universidad,1350,piso,60,0,1,False,Segunda mano/buen estado,True,Este,NaN,Calefacción individual,True,Distrito Centro,"Madrid capital, Madrid"
2,105407203,"Alquiler de piso en calle de las Aguas, 8",Palacio,2000,piso,98,3,1,False,Segunda mano/buen estado,False,NaN,NaN,NaN,True,Distrito Centro,"Madrid capital, Madrid"
3,99564765,Alquiler de piso en travesía de Trujillos,Sol,1580,piso,50,0,1,False,Segunda mano/buen estado,True,Sur,NaN,Eléctrica,True,Distrito Centro,"Madrid capital, Madrid"
4,108651419,"Alquiler de piso en calle de Lavapiés, 40",Lavapiés-Embajadores,1850,piso,85,3,1,False,Segunda mano/buen estado,True,NaN,NaN,NaN,False,Distrito Centro,"Madrid capital, Madrid"

## funciones de deteccionde los diferentes datos

In [27]:
datos_alquiler_l["precio_m2"] = datos_alquiler_l["precio"] / datos_alquiler_l["m2"]

# Redondear si quieres
datos_alquiler_l["precio_m2"] = datos_alquiler_l["precio_m2"].round(2)

# Ver primeras filas
print(datos_alquiler_l[["precio", "m2", "precio_m2"]].head())

   precio  m2  precio_m2
0    1300  47      27.66
1    1350  60      22.50
2    2000  98      20.41
3    1580  50      31.60
4    1850  85      21.76

In [28]:
datos_alquiler_l.head(5)

,id,titulo,localización,precio,vivienda,m2,habitaciones,baños,terraza,estado,armarios_empotrados,orientacion,año_construccion,calefaccion,aire_acondicionado,distrito,municipio,precio_m2
0,108649983,"Alquiler de piso en calle de Juanelo, 23",Lavapiés-Embajadores,1300,piso,47,0,1,False,Segunda mano/buen estado,True,Sur,NaN,NaN,True,Distrito Centro,"Madrid capital, Madrid",27.66
1,100086672,Alquiler de piso en Vicente Ferrer,Malasaña-Universidad,1350,piso,60,0,1,False,Segunda mano/buen estado,True,Este,NaN,Calefacción individual,True,Distrito Centro,"Madrid capital, Madrid",22.50
2,105407203,"Alquiler de piso en calle de las Aguas, 8",Palacio,2000,piso,98,3,1,False,Segunda mano/buen estado,False,NaN,NaN,NaN,True,Distrito Centro,"Madrid capital, Madrid",20.41
3,99564765,Alquiler de piso en travesía de Trujillos,Sol,1580,piso,50,0,1,False,Segunda mano/buen estado,True,Sur,NaN,Eléctrica,True,Distrito Centro,"Madrid capital, Madrid",31.60
4,108651419,"Alquiler de piso en calle de Lavapiés, 40",Lavapiés-Embajadores,1850,piso,85,3,1,False,Segunda mano/buen estado,True,NaN,NaN,NaN,False,Distrito Centro,"Madrid capital, Madrid",21.76

# EDA

In [29]:
datos_alquiler_l['vivienda'].unique()

array(['piso', 'estudio', 'ático', 'dúplex', 'casa', 'chalet'],
      dtype=object)

In [30]:
def clasificar_vivienda(vivienda):
    if vivienda in ['piso', 'ático', 'estudio', 'Dúplex']:
        return 'Piso'
    elif vivienda == ['casa' 'chalet' 'finca' 'caserón']:
        return 'Casa'
    else:
        return 'other'  # O puedes usar 'desconocido' si prefieres

# Crear la nueva columna
datos_alquiler_l['tipo_vivienda'] = datos_alquiler_l['vivienda'].apply(clasificar_vivienda)

In [31]:
datos_alquiler_l.drop(columns=['id', 'titulo', 'localización', 'orientacion' ], inplace= True)

In [32]:
datos_alquiler_l.head(5)

,precio,vivienda,m2,habitaciones,baños,terraza,estado,armarios_empotrados,año_construccion,calefaccion,aire_acondicionado,distrito,municipio,precio_m2,tipo_vivienda
0,1300,piso,47,0,1,False,Segunda mano/buen estado,True,NaN,NaN,True,Distrito Centro,"Madrid capital, Madrid",27.66,Piso
1,1350,piso,60,0,1,False,Segunda mano/buen estado,True,NaN,Calefacción individual,True,Distrito Centro,"Madrid capital, Madrid",22.50,Piso
2,2000,piso,98,3,1,False,Segunda mano/buen estado,False,NaN,NaN,True,Distrito Centro,"Madrid capital, Madrid",20.41,Piso
3,1580,piso,50,0,1,False,Segunda mano/buen estado,True,NaN,Eléctrica,True,Distrito Centro,"Madrid capital, Madrid",31.60,Piso
4,1850,piso,85,3,1,False,Segunda mano/buen estado,True,NaN,NaN,False,Distrito Centro,"Madrid capital, Madrid",21.76,Piso

In [33]:
datos_alquiler_l.shape

(7442, 15)

In [34]:
datos_alquiler_l.isnull().sum()

precio                    0
vivienda                  0
m2                        0
habitaciones              0
baños                     0
terraza                   0
estado                   27
armarios_empotrados       0
año_construccion       4881
calefaccion            1775
aire_acondicionado        0
distrito                135
municipio                68
precio_m2                 0
tipo_vivienda             0
dtype: int64

In [35]:
datos_alquiler_l.drop(columns=['terraza', 'año_construccion', 'calefaccion' ], inplace= True)

In [36]:
datos_alquiler_l.head(5)

,precio,vivienda,m2,habitaciones,baños,estado,armarios_empotrados,aire_acondicionado,distrito,municipio,precio_m2,tipo_vivienda
0,1300,piso,47,0,1,Segunda mano/buen estado,True,True,Distrito Centro,"Madrid capital, Madrid",27.66,Piso
1,1350,piso,60,0,1,Segunda mano/buen estado,True,True,Distrito Centro,"Madrid capital, Madrid",22.50,Piso
2,2000,piso,98,3,1,Segunda mano/buen estado,False,True,Distrito Centro,"Madrid capital, Madrid",20.41,Piso
3,1580,piso,50,0,1,Segunda mano/buen estado,True,True,Distrito Centro,"Madrid capital, Madrid",31.60,Piso
4,1850,piso,85,3,1,Segunda mano/buen estado,True,False,Distrito Centro,"Madrid capital, Madrid",21.76,Piso

In [37]:
datos_alquiler_l["municipio"].unique()

array(['Madrid capital, Madrid', 'Majadahonda', 'Pozuelo de Alarcón',
       'Las Rozas de Madrid', 'Collado Villalba',
       'Villanueva de la Cañada', nan, 'Paracuellos de Jarama',
       'La Moraleja', 'Pedrezuela', 'San Sebastián de los Reyes',
       'Alcobendas', 'Valdetorres de Jarama', 'Colmenar Viejo',
       'Tres Cantos', 'Ciudalcampo', 'Talamanca de Jarama',
       'San Agustin de Guadalix', 'Fuente el Saz de Jarama',
       'Miraflores de la Sierra', 'Club de Campo', 'Buitrago del Lozoya',
       'Valdelagua', 'Cobeña', 'Fuente del Fresno', 'Santo Domingo',
       'Venturada', 'Cotos de Monterrey', 'Guadalix de la Sierra',
       'Algete', 'Ajalvir', 'Valdeavero', 'El Molar',
       'Valdeolmos-Alalpardo', 'Valdemanco', 'El Vellón',
       'Manzanares el Real', 'Soto del Real', 'Puebla de la Sierra',
       'La Cabrera', 'Torrelaguna', 'Bustarviejo'], dtype=object)

In [38]:
datos_alquiler_l.head(5)

,precio,vivienda,m2,habitaciones,baños,estado,armarios_empotrados,aire_acondicionado,distrito,municipio,precio_m2,tipo_vivienda
0,1300,piso,47,0,1,Segunda mano/buen estado,True,True,Distrito Centro,"Madrid capital, Madrid",27.66,Piso
1,1350,piso,60,0,1,Segunda mano/buen estado,True,True,Distrito Centro,"Madrid capital, Madrid",22.50,Piso
2,2000,piso,98,3,1,Segunda mano/buen estado,False,True,Distrito Centro,"Madrid capital, Madrid",20.41,Piso
3,1580,piso,50,0,1,Segunda mano/buen estado,True,True,Distrito Centro,"Madrid capital, Madrid",31.60,Piso
4,1850,piso,85,3,1,Segunda mano/buen estado,True,False,Distrito Centro,"Madrid capital, Madrid",21.76,Piso

In [39]:
datos_alquiler_l.to_csv("datos_alquiler.csv", index=False, sep=";")

In [40]:
datos_alquiler_l.head(5)

,precio,vivienda,m2,habitaciones,baños,estado,armarios_empotrados,aire_acondicionado,distrito,municipio,precio_m2,tipo_vivienda
0,1300,piso,47,0,1,Segunda mano/buen estado,True,True,Distrito Centro,"Madrid capital, Madrid",27.66,Piso
1,1350,piso,60,0,1,Segunda mano/buen estado,True,True,Distrito Centro,"Madrid capital, Madrid",22.50,Piso
2,2000,piso,98,3,1,Segunda mano/buen estado,False,True,Distrito Centro,"Madrid capital, Madrid",20.41,Piso
3,1580,piso,50,0,1,Segunda mano/buen estado,True,True,Distrito Centro,"Madrid capital, Madrid",31.60,Piso
4,1850,piso,85,3,1,Segunda mano/buen estado,True,False,Distrito Centro,"Madrid capital, Madrid",21.76,Piso