In [19]:
import pandas as pd
import numpy as np
from ast import literal_eval
import re

In [20]:
pd.set_option('display.max_columns', None)

In [21]:
ruta = "C:\\Users\\LENOVO\\Desktop\\git hub\\PROYECTO FINAL\\Proyecto-final-vivienda-Madrid-Malaga-Sevilla\\bloque 3\\ALQUILER\\ANALISIS\\datos_analizar_alquiler.csv"
datos_alquiler = pd.read_csv(ruta)
datos_alquiler.head(5)

,id,Planta,Ascensor,EXT-INT,titulo,localización,precio,superficie_m2,habitaciones,baños,terraza,estado,armarios_empotrados,orientacion,año_construccion,calefaccion,aire_acondicionado,direccion,distrito,municipio,zona
0,108701668,1,NaN,Interior,Alquiler de estudio en calle de Juan Pantoja,Bellas Vistas,950,27,NaN,NaN,False,Segunda mano/buen estado,False,NaN,NaN,Bomba de frío/calor,True,Calle de Juan Pantoja,Distrito Tetuán,"Madrid capital, Madrid",NaN
1,108235202,1,NaN,NaN,Alquiler de piso en calle Manuela Mínguez,Valdeacederas,1245,46,2.0,NaN,True,Segunda mano/buen estado,False,NaN,NaN,Bomba de frío/calor,True,Calle Manuela Mínguez,Distrito Tetuán,"Madrid capital, Madrid",NaN
2,108235202,1,NaN,NaN,Alquiler de piso en calle Manuela Mínguez,Valdeacederas,1245,46,2.0,NaN,True,Segunda mano/buen estado,False,NaN,NaN,Bomba de frío/calor,True,Calle Manuela Mínguez,Distrito Tetuán,"Madrid capital, Madrid",NaN
3,108701668,1,NaN,Interior,Alquiler de estudio en calle de Juan Pantoja,Bellas Vistas,950,27,NaN,NaN,False,Segunda mano/buen estado,False,NaN,NaN,Bomba de frío/calor,True,Calle de Juan Pantoja,Distrito Tetuán,"Madrid capital, Madrid",NaN
4,108235202,1,NaN,NaN,Alquiler de piso en calle Manuela Mínguez,Valdeacederas,1245,46,2.0,NaN,True,Segunda mano/buen estado,False,NaN,NaN,Bomba de frío/calor,True,Calle Manuela Mínguez,Distrito Tetuán,"Madrid capital, Madrid",NaN

In [22]:
# Eliminar columnas
columnas_a_eliminar = [
    'direccion',
    'zona',
]
datos_alquiler.drop(columns=columnas_a_eliminar, inplace=True)

In [23]:
# Renombrar columna a m2
datos_alquiler.rename(columns={
    'superficie_m2': 'm2'
}, inplace=True)

In [24]:
datos_alquiler.head(5)

,id,Planta,Ascensor,EXT-INT,titulo,localización,precio,m2,habitaciones,baños,terraza,estado,armarios_empotrados,orientacion,año_construccion,calefaccion,aire_acondicionado,distrito,municipio
0,108701668,1,NaN,Interior,Alquiler de estudio en calle de Juan Pantoja,Bellas Vistas,950,27,NaN,NaN,False,Segunda mano/buen estado,False,NaN,NaN,Bomba de frío/calor,True,Distrito Tetuán,"Madrid capital, Madrid"
1,108235202,1,NaN,NaN,Alquiler de piso en calle Manuela Mínguez,Valdeacederas,1245,46,2.0,NaN,True,Segunda mano/buen estado,False,NaN,NaN,Bomba de frío/calor,True,Distrito Tetuán,"Madrid capital, Madrid"
2,108235202,1,NaN,NaN,Alquiler de piso en calle Manuela Mínguez,Valdeacederas,1245,46,2.0,NaN,True,Segunda mano/buen estado,False,NaN,NaN,Bomba de frío/calor,True,Distrito Tetuán,"Madrid capital, Madrid"
3,108701668,1,NaN,Interior,Alquiler de estudio en calle de Juan Pantoja,Bellas Vistas,950,27,NaN,NaN,False,Segunda mano/buen estado,False,NaN,NaN,Bomba de frío/calor,True,Distrito Tetuán,"Madrid capital, Madrid"
4,108235202,1,NaN,NaN,Alquiler de piso en calle Manuela Mínguez,Valdeacederas,1245,46,2.0,NaN,True,Segunda mano/buen estado,False,NaN,NaN,Bomba de frío/calor,True,Distrito Tetuán,"Madrid capital, Madrid"

## funciones de deteccionde los diferentes datos

In [25]:
datos_alquiler["precio_m2"] = datos_alquiler["precio"] / datos_alquiler["m2"]

# Redondear si quieres
datos_alquiler["precio_m2"] = datos_alquiler["precio_m2"].round(2)

# Ver primeras filas
print(datos_alquiler[["precio", "m2", "precio_m2"]].head())

   precio  m2  precio_m2
0     950  27      35.19
1    1245  46      27.07
2    1245  46      27.07
3     950  27      35.19
4    1245  46      27.07

In [26]:
datos_alquiler.head(5)

,id,Planta,Ascensor,EXT-INT,titulo,localización,precio,m2,habitaciones,baños,terraza,estado,armarios_empotrados,orientacion,año_construccion,calefaccion,aire_acondicionado,distrito,municipio,precio_m2
0,108701668,1,NaN,Interior,Alquiler de estudio en calle de Juan Pantoja,Bellas Vistas,950,27,NaN,NaN,False,Segunda mano/buen estado,False,NaN,NaN,Bomba de frío/calor,True,Distrito Tetuán,"Madrid capital, Madrid",35.19
1,108235202,1,NaN,NaN,Alquiler de piso en calle Manuela Mínguez,Valdeacederas,1245,46,2.0,NaN,True,Segunda mano/buen estado,False,NaN,NaN,Bomba de frío/calor,True,Distrito Tetuán,"Madrid capital, Madrid",27.07
2,108235202,1,NaN,NaN,Alquiler de piso en calle Manuela Mínguez,Valdeacederas,1245,46,2.0,NaN,True,Segunda mano/buen estado,False,NaN,NaN,Bomba de frío/calor,True,Distrito Tetuán,"Madrid capital, Madrid",27.07
3,108701668,1,NaN,Interior,Alquiler de estudio en calle de Juan Pantoja,Bellas Vistas,950,27,NaN,NaN,False,Segunda mano/buen estado,False,NaN,NaN,Bomba de frío/calor,True,Distrito Tetuán,"Madrid capital, Madrid",35.19
4,108235202,1,NaN,NaN,Alquiler de piso en calle Manuela Mínguez,Valdeacederas,1245,46,2.0,NaN,True,Segunda mano/buen estado,False,NaN,NaN,Bomba de frío/calor,True,Distrito Tetuán,"Madrid capital, Madrid",27.07

In [27]:
datos_alquiler['vivienda'] = datos_alquiler['titulo'].apply(lambda x: str(x).split()[2] if pd.notnull(x) and len(str(x).split()) > 0 else None)

# EDA

In [28]:
datos_alquiler.head(5)

,id,Planta,Ascensor,EXT-INT,titulo,localización,precio,m2,habitaciones,baños,terraza,estado,armarios_empotrados,orientacion,año_construccion,calefaccion,aire_acondicionado,distrito,municipio,precio_m2,vivienda
0,108701668,1,NaN,Interior,Alquiler de estudio en calle de Juan Pantoja,Bellas Vistas,950,27,NaN,NaN,False,Segunda mano/buen estado,False,NaN,NaN,Bomba de frío/calor,True,Distrito Tetuán,"Madrid capital, Madrid",35.19,estudio
1,108235202,1,NaN,NaN,Alquiler de piso en calle Manuela Mínguez,Valdeacederas,1245,46,2.0,NaN,True,Segunda mano/buen estado,False,NaN,NaN,Bomba de frío/calor,True,Distrito Tetuán,"Madrid capital, Madrid",27.07,piso
2,108235202,1,NaN,NaN,Alquiler de piso en calle Manuela Mínguez,Valdeacederas,1245,46,2.0,NaN,True,Segunda mano/buen estado,False,NaN,NaN,Bomba de frío/calor,True,Distrito Tetuán,"Madrid capital, Madrid",27.07,piso
3,108701668,1,NaN,Interior,Alquiler de estudio en calle de Juan Pantoja,Bellas Vistas,950,27,NaN,NaN,False,Segunda mano/buen estado,False,NaN,NaN,Bomba de frío/calor,True,Distrito Tetuán,"Madrid capital, Madrid",35.19,estudio
4,108235202,1,NaN,NaN,Alquiler de piso en calle Manuela Mínguez,Valdeacederas,1245,46,2.0,NaN,True,Segunda mano/buen estado,False,NaN,NaN,Bomba de frío/calor,True,Distrito Tetuán,"Madrid capital, Madrid",27.07,piso

In [29]:
datos_alquiler["vivienda"].unique()

array(['estudio', 'piso', 'ático', 'dúplex'], dtype=object)

In [33]:
datos_alquiler.drop(columns=['id', 'titulo', 'localización', 'orientacion' ], inplace= True)

In [37]:
datos_alquiler.head(5)

,Planta,Ascensor,EXT-INT,precio,m2,habitaciones,baños,terraza,estado,armarios_empotrados,año_construccion,calefaccion,aire_acondicionado,distrito,municipio,precio_m2,vivienda
0,1,NaN,Interior,950,27,NaN,NaN,False,Segunda mano/buen estado,False,NaN,Bomba de frío/calor,True,Distrito Tetuán,"Madrid capital, Madrid",35.19,estudio
1,1,NaN,NaN,1245,46,2.0,NaN,True,Segunda mano/buen estado,False,NaN,Bomba de frío/calor,True,Distrito Tetuán,"Madrid capital, Madrid",27.07,piso
2,1,NaN,NaN,1245,46,2.0,NaN,True,Segunda mano/buen estado,False,NaN,Bomba de frío/calor,True,Distrito Tetuán,"Madrid capital, Madrid",27.07,piso
3,1,NaN,Interior,950,27,NaN,NaN,False,Segunda mano/buen estado,False,NaN,Bomba de frío/calor,True,Distrito Tetuán,"Madrid capital, Madrid",35.19,estudio
4,1,NaN,NaN,1245,46,2.0,NaN,True,Segunda mano/buen estado,False,NaN,Bomba de frío/calor,True,Distrito Tetuán,"Madrid capital, Madrid",27.07,piso

In [34]:
datos_alquiler.shape

(9820, 17)

In [36]:
datos_alquiler.isnull().sum()

Planta                  236
Ascensor                225
EXT-INT                  58
precio                    0
m2                        0
habitaciones           3659
baños                  5092
terraza                   0
estado                   48
armarios_empotrados       0
año_construccion       6523
calefaccion            4302
aire_acondicionado        0
distrito                 88
municipio                50
precio_m2                 0
vivienda                  0
dtype: int64

In [ ]:
print(datos_alquiler["ubicacion"].head(20).tolist())

[['Calle de Juanelo, 23', 'Barrio Lavapiés-Embajadores', 'Distrito Centro', 'Madrid', 'Madrid capital, Madrid'], ['Vicente Ferrer', 'Barrio Malasaña-Universidad', 'Distrito Centro', 'Madrid', 'Madrid capital, Madrid'], ['Calle de las Aguas, 8', 'Barrio Palacio', 'Distrito Centro', 'Madrid', 'Madrid capital, Madrid'], ['Travesía de Trujillos', 'Barrio Sol', 'Distrito Centro', 'Madrid', 'Madrid capital, Madrid'], ['Calle de Lavapiés, 40', 'Barrio Lavapiés-Embajadores', 'Distrito Centro', 'Madrid', 'Madrid capital, Madrid'], ['Calle JESUS DEL VALLE', 'Barrio Malasaña-Universidad', 'Distrito Centro', 'Madrid', 'Madrid capital, Madrid'], ['Gran Vía, 78', 'Barrio Malasaña-Universidad', 'Distrito Centro', 'Madrid', 'Madrid capital, Madrid'], ['Calle de Hernán Cortés', 'Barrio Chueca-Justicia', 'Distrito Centro', 'Madrid', 'Madrid capital, Madrid'], ['Calle del Amparo, 84', 'Barrio Lavapiés-Embajadores', 'Distrito Centro', 'Madrid', 'Madrid capital, Madrid'], ['Calle de Buenavista', 'Barrio Lavapiés-Embajadores', 'Distrito Centro', 'Madrid', 'Madrid capital, Madrid'], ['Calle del Carnero, 16', 'Barrio Lavapiés-Embajadores', 'Distrito Centro', 'Madrid', 'Madrid capital, Madrid'], ['Calle del Príncipe', 'Barrio Huertas-Cortes', 'Distrito Centro', 'Madrid', 'Madrid capital, Madrid'], ['Calle de la Palma', 'Barrio Malasaña-Universidad', 'Distrito Centro', 'Madrid', 'Madrid capital, Madrid'], ['Calle de Pelayo', 'Barrio Chueca-Justicia', 'Distrito Centro', 'Madrid', 'Madrid capital, Madrid'], ['Calle del Humilladero', 'Barrio Palacio', 'Distrito Centro', 'Madrid', 'Madrid capital, Madrid'], ['Calle del Limón, 32', 'Barrio Malasaña-Universidad', 'Distrito Centro', 'Madrid', 'Madrid capital, Madrid'], ['Calle del Caballero de Gracia', 'Barrio Sol', 'Distrito Centro', 'Madrid', 'Madrid capital, Madrid'], ['Calle de las Tres Cruces', 'Barrio Sol', 'Distrito Centro', 'Madrid', 'Madrid capital, Madrid'], ['Plaza de Carlos Cambronero, 4', 'Barrio Malasaña-Universidad', 'Distrito Centro', 'Madrid', 'Madrid capital, Madrid'], ['Calle del Príncipe', 'Barrio Huertas-Cortes', 'Distrito Centro', 'Madrid', 'Madrid capital, Madrid']]

In [ ]:
datos_alquiler["ubicacion"] = datos_alquiler["ubicacion"].astype(str)

In [ ]:
datos_alquiler["ciudad"]   = datos_alquiler["ubicacion"].str.split(",").str[-3].str.strip()
datos_alquiler["distrito"] = datos_alquiler["ubicacion"].str.split(",").str[-4].str.strip()
datos_alquiler["barrio"]   = datos_alquiler["ubicacion"].str.split(",").str[-5].str.strip()

In [ ]:
datos_alquiler.head(5)

,precio,ubicacion,m2,habitaciones,baño,terraza,estado,armarios,calefaccion,garaje,trastero,aire acondicionado,vivienda,ciudad,distrito,barrio
0,1300,"['Calle de Juanelo, 23', 'Barrio Lavapiés-Emba...",47,1,1,0,Segunda mano/buen estado,1,0,0,0,0,piso,'Madrid','Distrito Centro','Barrio Lavapiés-Embajadores'
1,1350,"['Vicente Ferrer', 'Barrio Malasaña-Universida...",60,1,1,0,Segunda mano/buen estado,1,1,0,0,0,piso,'Madrid','Distrito Centro','Barrio Malasaña-Universidad'
2,2000,"['Calle de las Aguas, 8', 'Barrio Palacio', 'D...",98,3,1,0,Segunda mano/buen estado,0,0,0,0,0,piso,'Madrid','Distrito Centro','Barrio Palacio'
3,1580,"['Travesía de Trujillos', 'Barrio Sol', 'Distr...",50,1,1,0,Segunda mano/buen estado,1,1,0,0,0,piso,'Madrid','Distrito Centro','Barrio Sol'
4,1850,"['Calle de Lavapiés, 40', 'Barrio Lavapiés-Emb...",85,3,1,0,Segunda mano/buen estado,1,0,0,0,0,piso,'Madrid','Distrito Centro','Barrio Lavapiés-Embajadores'

In [ ]:
datos_alquiler["ciudad"].unique()

array(["'Madrid'", "'Majadahonda'", "'Pozuelo de Alarcón'",
       "'Las Rozas de Madrid'", "'Collado Villalba'",
       "'Villanueva de la Cañada'", "['Distrito Villanueva de la Cañada'",
       "'Paracuellos de Jarama'", "'La Moraleja'", "'Pedrezuela'",
       "'San Sebastián de los Reyes'", "'Alcobendas'",
       "'Valdetorres de Jarama'", "'Colmenar Viejo'", "'Tres Cantos'",
       "'Ciudalcampo'", "'Talamanca de Jarama'", nan,
       "'San Agustin de Guadalix'", "'Fuente el Saz de Jarama'",
       "'Miraflores de la Sierra'", "'Club de Campo'",
       "'Buitrago del Lozoya'", "'Valdelagua'", "'Cobeña'",
       "'Fuente del Fresno'", "'Santo Domingo'", "'Venturada'",
       "'Cotos de Monterrey'", "'Guadalix de la Sierra'", "'Algete'",
       "'Ajalvir'", "'Valdeavero'", "'El Molar'",
       "'Valdeolmos-Alalpardo'", "'Valdemanco'", "'El Vellón'",
       "'Manzanares el Real'", "'Soto del Real'", "'Puebla de la Sierra'",
       "'La Cabrera'", "'Torrelaguna'", "'Bustarviejo'"], dtype=object)

In [ ]:
datos_alquiler.drop(columns=['ubicacion'], inplace= True)

In [ ]:
datos_alquiler.head(5)

,precio,m2,habitaciones,baño,terraza,estado,armarios,calefaccion,garaje,trastero,aire acondicionado,vivienda,ciudad,distrito,barrio
0,1300,47,1,1,0,Segunda mano/buen estado,1,0,0,0,0,piso,'Madrid','Distrito Centro','Barrio Lavapiés-Embajadores'
1,1350,60,1,1,0,Segunda mano/buen estado,1,1,0,0,0,piso,'Madrid','Distrito Centro','Barrio Malasaña-Universidad'
2,2000,98,3,1,0,Segunda mano/buen estado,0,0,0,0,0,piso,'Madrid','Distrito Centro','Barrio Palacio'
3,1580,50,1,1,0,Segunda mano/buen estado,1,1,0,0,0,piso,'Madrid','Distrito Centro','Barrio Sol'
4,1850,85,3,1,0,Segunda mano/buen estado,1,0,0,0,0,piso,'Madrid','Distrito Centro','Barrio Lavapiés-Embajadores'

In [ ]:
datos_alquiler["distrito"] = (
    datos_alquiler["distrito"]
    .astype(str)                          # asegurar que es texto
    .str.replace("'", "", regex=False)    # eliminar comillas simples
    .str.strip()                          # quitar espacios extra
)
datos_alquiler["barrio"] = (
    datos_alquiler["barrio"]
    .astype(str)                          # asegurar que es texto
    .str.replace("'", "", regex=False)    # eliminar comillas simples
    .str.strip()                          # quitar espacios extra
)

datos_alquiler["ciudad"] = (
    datos_alquiler["ciudad"]
    .astype(str)                          # asegurar que es texto
    .str.replace("'", "", regex=False)    # eliminar comillas simples
    .str.strip()                          # quitar espacios extra
)

In [ ]:

datos_alquiler["distrito"] = (
    datos_alquiler["distrito"]
    .astype(str)
    .str.split(" ", n=1)   # separa en 2 partes: primera palabra + resto
    .str[1]                # se queda con la segunda parte
    .str.strip())

In [ ]:
datos_alquiler["barrio"] = (
    datos_alquiler["barrio"]
    .astype(str)
    .str.split(" ", n=1)   # separa en 2 partes: primera palabra + resto
    .str[1]                # se queda con la segunda parte
    .str.strip())

In [ ]:
datos_alquiler["ciudad"].unique()

array(['Madrid', 'Majadahonda', 'Pozuelo de Alarcón',
       'Las Rozas de Madrid', 'Collado Villalba',
       'Villanueva de la Cañada', '[Distrito Villanueva de la Cañada',
       'Paracuellos de Jarama', 'La Moraleja', 'Pedrezuela',
       'San Sebastián de los Reyes', 'Alcobendas',
       'Valdetorres de Jarama', 'Colmenar Viejo', 'Tres Cantos',
       'Ciudalcampo', 'Talamanca de Jarama', 'nan',
       'San Agustin de Guadalix', 'Fuente el Saz de Jarama',
       'Miraflores de la Sierra', 'Club de Campo', 'Buitrago del Lozoya',
       'Valdelagua', 'Cobeña', 'Fuente del Fresno', 'Santo Domingo',
       'Venturada', 'Cotos de Monterrey', 'Guadalix de la Sierra',
       'Algete', 'Ajalvir', 'Valdeavero', 'El Molar',
       'Valdeolmos-Alalpardo', 'Valdemanco', 'El Vellón',
       'Manzanares el Real', 'Soto del Real', 'Puebla de la Sierra',
       'La Cabrera', 'Torrelaguna', 'Bustarviejo'], dtype=object)

In [ ]:
datos_alquiler.rename(columns={"baño": "baños"}, inplace=True)

In [ ]:
datos_alquiler.to_csv("datos_alquiler.csv", index=False, sep=";")

In [ ]:
datos_alquiler.head(5)

,precio,m2,habitaciones,baños,terraza,estado,armarios,calefaccion,garaje,trastero,aire acondicionado,vivienda,ciudad,distrito,barrio
0,1300,47,1,1,0,Segunda mano/buen estado,1,0,0,0,0,piso,Madrid,Centro,Lavapiés-Embajadores
1,1350,60,1,1,0,Segunda mano/buen estado,1,1,0,0,0,piso,Madrid,Centro,Malasaña-Universidad
2,2000,98,3,1,0,Segunda mano/buen estado,0,0,0,0,0,piso,Madrid,Centro,Palacio
3,1580,50,1,1,0,Segunda mano/buen estado,1,1,0,0,0,piso,Madrid,Centro,Sol
4,1850,85,3,1,0,Segunda mano/buen estado,1,0,0,0,0,piso,Madrid,Centro,Lavapiés-Embajadores